### ISSUE TITLE
Milestone 2 Feedback: Mechanics

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI522_GR406#43]
Very organized and concise README, great job!

- [x] For directory structure, I would suggest:
	- [x] having the `fig` folder within the `results` folder
	- [x] having a separate EDA folder within the `src` folder

- [x] The flowchart is good, but it can be more clear and concise if you do not repeat the same entity. For example, instead of visualizing the `Raw data output file` twice, just draw a black arrow from the first one directly to the `src/data_cleaning.R` script.

**Comment by zanderhinton** [comment]
- restructured directory and edited flowchart based on suggestions.
