### ISSUE TITLE
Milestone 2 Feedback: Viz

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI522_GR406#44]
- [x] Your first graph is a time series, so I would suggest connecting the dots, thus using a line instead of points.

- [x] You can take a look at the `stargazer` package in R to present your regression results.

- [x] In your third graph, I would suggest using a different colour scale as the blue is hard to distinguish.

- [x] Always add titles to graphs and tables.

**Comment by zanderhinton** [comment]
Had issues with stargazer tables rendering in .md and on github. Ended up tidying up table and displaying regression results in a much more readable fashion.
